# ===================================================================
# CONFIGURAÇÃO DE CONEXÃO DO BANCO DE DADOS (POSTGRESQL)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=12345

# ===================================================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ===================================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Como ainda não criamos as nossas tabelas de Produto, deixamos como 'none' ou 'update'
spring.jpa.hibernate.ddl-auto=update

# ===================================================================
# CONFIGURAÇÕES DE E-MAIL (GMAIL SMTP)
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gustavorochagtat3022@gmail.com
# IMPORTANTE: Leia o aviso abaixo sobre a senha!
spring.mail.password=msxp hruj dqhe zzsu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true